# Generated by Django 5.0.3 on 2024-03-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_personaldetails_delete_user_delete_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('question_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('experience', models.TextField()),
                ('expenditure', models.TextField()),
                ('fishpond', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'unique_together': {('user_id', 'question')},
            },
        ),
    ]
