# Generated by Django 5.0.3 on 2024-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_fishtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishtypes',
            name='fish_size',
            field=models.IntegerField(default=0),
        ),
    ]
