# Generated by Django 5.0.3 on 2024-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_fishtypes_fish_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishtypes',
            name='fish_size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fishtypes',
            name='maturity_period',
            field=models.TextField(),
        ),
    ]
