# Generated by Django 5.0.3 on 2024-03-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_alter_fishtypes_fish_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('youtubeUrl', models.URLField()),
            ],
        ),
    ]
