# Generated by Django 5.0.3 on 2024-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_pond'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('impact', models.TextField()),
                ('imgUrl', models.URLField()),
                ('treatement_method', models.TextField()),
                ('medication_type', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('treatment_duration', models.CharField(max_length=100)),
                ('prevention_strategies', models.TextField()),
                ('types_of_fish_affected_mostly', models.TextField()),
            ],
        ),
    ]
