# Generated by Django 5.0.3 on 2024-03-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='treatement_method',
            new_name='treatment_method',
        ),
    ]
