# Generated by Django 5.0.3 on 2024-03-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_rename_treatement_method_disease_treatment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.TextField(default='bacterial diseases'),
            preserve_default=False,
        ),
    ]
